# Generated by Django 5.2 on 2025-05-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEnquiryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255, verbose_name='Enter your names')),
                ('email', models.CharField(max_length=255, verbose_name='Enter your email')),
                ('phone', models.CharField(max_length=255, verbose_name='Enter your phone')),
                ('enquiry', models.CharField(max_length=255, verbose_name='Enter your request')),
            ],
        ),
    ]
