# Generated by Django 5.1.3 on 2026-07-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_room_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEnquiryForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "names",
                    models.CharField(max_length=255, verbose_name="Enter your names"),
                ),
                (
                    "email",
                    models.CharField(max_length=255, verbose_name="Enter your email"),
                ),
                (
                    "phone",
                    models.CharField(max_length=255, verbose_name="Enter your phone"),
                ),
                (
                    "enquiry",
                    models.CharField(max_length=255, verbose_name="Enter your request"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserEnquiryModel",
        ),
    ]
