# Generated by Django 5.2 on 2025-05-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=100, verbose_name='Hotel')),
                ('names', models.CharField(max_length=100, verbose_name='Names')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone ')),
                ('chk_in', models.CharField(max_length=100, verbose_name='Check in')),
                ('chk_out', models.CharField(max_length=100, verbose_name='Check out')),
                ('guest', models.CharField(max_length=100, verbose_name='Number of guests')),
            ],
        ),
    ]
