# Generated by Django 5.2 on 2025-05-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='hotel',
            field=models.CharField(max_length=100, verbose_name='Select Hotel'),
        ),
    ]
