# Generated by Django 5.1.3 on 2026-07-05 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_alter_reservation_hotel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Room Number"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard Room"),
                            ("DELUXE", "Deluxe Room"),
                            ("SUITE", "Executive Suite"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Price per Night (₦)",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserEnquiryForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "names",
                    models.CharField(max_length=255, verbose_name="Enter your names"),
                ),
                (
                    "email",
                    models.CharField(max_length=255, verbose_name="Enter your email"),
                ),
                (
                    "phone",
                    models.CharField(max_length=255, verbose_name="Enter your phone"),
                ),
                (
                    "enquiry",
                    models.CharField(max_length=255, verbose_name="Enter your request"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "paystack_reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservations.room",
                    ),
                ),
            ],
        ),
    ]
