# Generated by Django 5.1.3 on 2026-07-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_room_userenquiryform_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="category",
            field=models.CharField(
                choices=[
                    ("new_york", "New York Luxury Suite"),
                    ("paris", "Paris Boutique Room"),
                    ("shangrila", "Shangri-La"),
                    ("chatrium", "Chatrium"),
                    ("fourseasons", "Four Seasons"),
                    ("hilton", "Hilton"),
                ],
                default="hilton",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Room/ID Number"
            ),
        ),
    ]
