# Generated by Django 5.1.3 on 2026-07-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_alter_room_category_alter_room_room_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="price_per_night",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Price per Night ($)"
            ),
        ),
    ]
